sudo: required
language: generic

services:
 - docker

before_install:
 - docker build -t krs/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true krs/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
   secure: "$aws_access_key"
  secret_access_key:
   secure: "$aws_secret_key"
  region: "eu-north-1"
  app: "Frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-823689189933"
  bucket_path: "Frontend"
  on:
    branch: main
